/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 
 The sidebars can be generated from the filesystem, or explicitly defined here.
 
 Create as many sidebars as you want.
 */

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    
    tutorialSidebar: [
        'getting-started',
        {
            type: 'category',
            label: 'Pricing Integration',
            link: {type: 'doc', id: 'pricing-integration/price-integration'},
            items: [
                {
                    type: 'category',
                    label: 'Shopify Plus',
                    items: [
                        'pricing-integration/shopify-plus/shop-plus-add-javascript',
                        'pricing-integration/shopify-plus/create-test',
                        'pricing-integration/shopify-plus/select-prices',
                        'pricing-integration/shopify-plus/checkout-script',
                        'pricing-integration/shopify-plus/update-cart',
                        'pricing-integration/shopify-plus/complete',
                    ],
                },
                {
                    type: 'category',
                    label: 'Non-Shopify Plus',
                    items: [
                        'pricing-integration/non-shopify-plus/non-plus-add-javascript',
                        'pricing-integration/non-shopify-plus/create-test',
                        'pricing-integration/non-shopify-plus/select-prices',
                        'pricing-integration/non-shopify-plus/activate-dup-products',
                        'pricing-integration/non-shopify-plus/complete',
                    ],
                },
                'pricing-integration/update-your-theme',
                'pricing-integration/integration-widget',
            ],
        },
        {
            type: 'category',
            label: 'Shipping Integration',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'shipping-integration',
                },
            ],
        },
        {
            type: 'category',
            label: 'Javascript API',
            link: {type: 'doc', id: 'javascript-api/intelligems-window-object'},
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'javascript-api/intelligems-window-object',
                },
            ],
        },
        {
            type: 'category',
            label: '3rd Party Integrations',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'third-party-integrations',
                },
            ],
        },
        'headless-integration/headless-integrations',
        'advanced-settings/advanced-settings',
    ],
    
    // But you can create a sidebar manually
    /*
     tutorialSidebar: [
     {
     type: 'category',
     label: 'Tutorial',
     items: ['hello'],
     },
     ],
     */
}
