/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 
 The sidebars can be generated from the filesystem, or explicitly defined here.
 
 Create as many sidebars as you want.
 */

module.exports = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
    
    tutorialSidebar: [
        'getting-started',
        {
            type: 'category',
            label: 'Pricing Integration',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'pricing-integration',
                },
            ],
        },
        {
            type: 'category',
            label: 'Shipping Integration',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'shipping-integration',
                },
            ],
        },
        {
            type: 'category',
            label: 'Javascript API',
            link: {type: 'doc', id: 'javascript-api/intelligems-window-object'},
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'javascript-api/intelligems-window-object',
                },
            ],
        },
        {
            type: 'category',
            label: '3rd Party Integrations',
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'third-party-integrations',
                },
            ],
        },
        'advanced-settings/advanced-settings',
    ],
    
    // But you can create a sidebar manually
    /*
     tutorialSidebar: [
     {
     type: 'category',
     label: 'Tutorial',
     items: ['hello'],
     },
     ],
     */
}
